### ISSUE TITLE
缺少依赖pil

### ISSUE THREAD

**Issue by aogg** [Do1e/mijia-api#14]
/ # python3 /hostTmp/python/mijiaAPI_run_scene.py
Scan the QR code below with Mi Home app
Traceback (most recent call last):
  File "/hostTmp/python/mijiaAPI_run_scene.py", line 8, in <module>
    auth = login.QRlogin()
  File "/usr/local/lib/python3.13/site-packages/mijiaAPI/login.py", line 132, in QRlogin
    self._print_qr(loginurl)
    ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/mijiaAPI/login.py", line 93, in _print_qr
    qr.make_image().save('qr.png')
    ~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/qrcode/main.py", line 363, in make_image
    from qrcode.image.pil import Image, PilImage
  File "/usr/local/lib/python3.13/site-packages/qrcode/image/pil.py", line 2, in <module>
    from PIL import Image, ImageDraw
ModuleNotFoundError: No module named 'PIL'

**Comment by Do1e** [comment]
```bash
pip install Pillow
```
